var students = [
  {name: "Charlotta Abrahamsson", class:"A",attendance: "63%"},
  {name: "Cecilia Lindgren", class:"A",attendance: "68%"},
  {name: "Gunnel Jonasson", class:"A",attendance: "55%"},
  {name: "David Holm", class:"A",attendance: "22%"},
  {name: "Margareta Eriksson", class:"A",attendance: "21%"},
  {name: "Ulrika Björk", class:"A",attendance: "68%"},
  {name: "Martin Lundqvist", class:"A",attendance: "54%"},
  {name: "Fredrik Lindberg", class:"A",attendance: "49%"},
  {name: "Birgit Hassan", class:"A",attendance: "14%"},
  {name: "Magnus Lind", class:"A",attendance: "23%"},
  {name: "Bengt Magnusson", class:"A",attendance: "7%"},
  {name: "Pia Hansen", class:"A",attendance: "96%"},
  {name: "Arne Eklund", class:"A",attendance: "21%"},
  {name: "Thomas Jakobsson", class:"A",attendance: "62%"},
  {name: "Roland Blomqvist", class:"A",attendance: "58%"},
  {name: "Charlotte Lund", class:"A",attendance: "3%"},
  {name: "Nils Svensson", class:"A",attendance: "3%"},
  {name: "Oskar Berg", class:"A",attendance: "42%"},
  {name: "Robin Sundberg", class:"A",attendance: "63%"},
  {name: "Lisbeth Åström", class:"A",attendance: "59%"},
  {name: "Anneli Bergqvist", class:"A",attendance: "28%"},
  {name: "Inga Hellström", class:"A",attendance: "84%"},
  {name: "Ellen Blom", class:"A",attendance: "51%"},
  {name: "Kurt Hedlund", class:"A",attendance: "46%"},
  {name: "Claes Nordström", class:"A",attendance: "52%"},
  {name: "Jonathan Ekström", class:"A",attendance: "84%"},
  {name: "Agnes Sundström", class:"A",attendance: "69%"},
  {name: "Kerstin Hansson", class:"A",attendance: "45%"},
  {name: "Elsa Bergman", class:"A",attendance: "3%"},
  {name: "Bo Olofsson", class:"A",attendance: "15%"},
  {name: "Kent Berggren", class:"A",attendance: "27%"},
  {name: "Anna Karlsson", class:"A",attendance: "93%"},
  {name: "Anders Nilsson", class:"A",attendance: "42%"},
  {name: "Caroline Nyström", class:"A",attendance: "71%"},
  {name: "Kristina Nilsson", class:"A",attendance: "65%"},
  {name: "Gunnar Bengtsson", class:"A",attendance: "43%"},
  {name: "Sara Lindberg", class:"A",attendance: "20%"},
  {name: "Julia Holmberg", class:"A",attendance: "98%"},
  {name: "Anita Lind", class:"A",attendance: "11%"},
  {name: "Emil Fransson", class:"A",attendance: "78%"},
  {name: "Johanna Olofsson", class:"A",attendance: "76%"},
  {name: "Mats Mattsson", class:"A",attendance: "82%"},
  {name: "Tobias Nordin", class:"A",attendance: "24%"},
  {name: "Ann-Marie Dahlberg", class:"A",attendance: "26%"},
  {name: "Frida Hermansson", class:"A",attendance: "84%"},
  {name: "Arvid Hassan", class:"A",attendance: "10%"},
  {name: "Linda Engström", class:"A",attendance: "7%"},
  {name: "Katarina Magnusson", class:"A",attendance: "46%"},

  {name:"Torbjörn Andreasson",class:"B", attendance:"5%"},
  {name:"Mikael Larsson",class:"B", attendance:"84%"},
  {name:"Sonja Andreasson",class:"B", attendance:"27%"},
  {name:"Inger Lindström",class:"B", attendance:"66%"},
  {name:"Sofie Fransson",class:"B", attendance:"45%"},
  {name:"Karin Persson",class:"B", attendance:"16%"},
  {name:"Anton Björklund",class:"B", attendance:"32%"},
  {name:"Leif Sandberg",class:"B", attendance:"35%"},
  {name:"Marcus Björk",class:"B", attendance:"14%"},
  {name:"Jenny Lundberg",class:"B", attendance:"79%"},
  {name:"Annika Lundin",class:"B", attendance:"77%"},
  {name:"Christer Bergström",class:"B", attendance:"60%"},
  {name:"Berit Åberg",class:"B", attendance:"57%"},
  {name:"Helena Jönsson",class:"B", attendance:"40%"},
  {name:"Rut Berggren",class:"B", attendance:"6%"},
  {name:"Matilda Gunnarsson",class:"B", attendance:"8%"},
  {name:"Dan Strömberg",class:"B", attendance:"14%"},
  {name:"Siv Löfgren",class:"B", attendance:"66%"},
  {name:"Jörgen Hermansson",class:"B", attendance:"73%"},
  {name:"Maja Ekström",class:"B", attendance:"84%"},
  {name:"Isabelle Falk",class:"B", attendance:"36%"},
  {name:"Alexandra Holmgren",class:"B", attendance:"49%"},
  {name:"Åsa Nyberg",class:"B", attendance:"52%"},
  {name:"Emma Jakobsson",class:"B", attendance:"80%"},
  {name:"Anette Samuelsson",class:"B", attendance:"31%"},
  {name:"Sebastian Viklund",class:"B", attendance:"36%"},
  {name:"Roger Pålsson",class:"B", attendance:"18%"},
  {name:"Åke Lindqvist",class:"B", attendance:"7%"},
  {name:"Helen Eklund",class:"B", attendance:"6%"},
  {name:"Linnéa Svensson",class:"B", attendance:"76%"},
  {name:"Ali Norberg",class:"B", attendance:"1%"},
  {name:"Lennart Jansson",class:"B", attendance:"88%"},
  {name:"Ingrid Pettersson",class:"B", attendance:"50%"},
  {name:"Marianne Jansson",class:"B", attendance:"51%"},
  {name:"Stefan Lundgren",class:"B", attendance:"16%"},
  {name:"Britt Eliasson",class:"B", attendance:"30%"},
  {name:"Maria Andersson",class:"B", attendance:"78%"},

  {name:"Joakim Söderberg",class:"C", attendance:"74%"},
  {name:"Josef Åkesson",class:"C", attendance:"30%"},
  {name:"Hugo Falk",class:"C", attendance:"20%"},
  {name:"Mattias Fredriksson",class:"C", attendance:"16%"},
  {name:"Linus Öberg",class:"C", attendance:"24%"},
  {name:"Axel Danielsson",class:"C", attendance:"100%"},
  {name:"Therese Lundgren",class:"C", attendance:"3%"},
  {name:"Elias Hellström",class:"C", attendance:"10%"},
  {name:"Amanda Mårtensson",class:"C", attendance:"91%"},
  {name:"Ludvig Sundström",class:"C", attendance:"10%"},
  {name:"Sofia Jonsson",class:"C", attendance:"24%"},
  {name:"Karl Andersson",class:"C", attendance:"45%"},
  {name:"Yvonne Lundström",class:"C", attendance:"88%"},
  {name:"Lucas Sjögren",class:"C", attendance:"67%"},
  {name:"Adam Abrahamsson",class:"C", attendance:"13%"},
  {name:"Karolina Mohamed",class:"C", attendance:"16%"},
  {name:"Oliver Hansen",class:"", attendance:"92%"},
  {name:"Astrid Isaksson",class:"C", attendance:"51%"},
  {name:"Emanuel Åberg",class:"C", attendance:"73%"},
  {name:"Johnny Martinsson",class:"C", attendance:"64%"},
  {name:"Per Eriksson",class:"C", attendance:"94%"},
  {name:"Louise Berglund",class:"C", attendance:"51%"},
  {name:"Elisabeth Johansson",class:"C", attendance:"67%"},
  {name:"Ebba Martinsson",class:"C", attendance:"97%"},
  {name:"Marie Gustafsson",class:"C", attendance:"22%"},
  {name:"Josefin Holm",class:"C", attendance:"37%"},
  {name:"John Berglund",class:"C", attendance:"82%"},
  {name:"Gösta Ek",class:"C", attendance:"51%"},
  {name:"Rickard Löfgren",class:"C", attendance:"90%"},
  {name:"Kenneth Ström",class:"C", attendance:"79%"},
  {name:"Ingemar Håkansson",class:"", attendance:"15%"},
  {name:"Andreas Lundberg",class:"C", attendance:"42%"},
  {name:"William Mårtensson",class:"C", attendance:"26%"},
  {name:"Stig Bergqvist",class:"C", attendance:"99%"},
  {name:"Agneta Viklund",class:"C", attendance:"16%"},
  {name:"Georg Blom",class:"C", attendance:"27%"},
  {name:"Kjell Wikström",class:"C", attendance:"92%"}
  

 ];

function createStudentRowElement(student){
	return "<tr><td>" + student.name + "</td><td>" + student.attendance + "</td></tr>";
}

function generateStudentList(){
	$.each(students, function(index, item){
  	if($("#ClassSelect").val() == item.class)
			$('.StudentListBody').append(createStudentRowElement(item));
	});
}

window.classChanged = function classChanged(){
	$('.StudentListBody').empty();
  generateStudentList();
}


//Code

generateStudentList();

